__dependency__: configs/base_config.yaml, configs/LF-Wikipedia-500K_10/dataset.yaml
expname: meta_clf_cluster_218_st_10
desc: "Training Meta-Classifier Genearator (MCG)"

# Base Encoder
base_retriever: "NGAME"

# Combiner parameters
num_neighbors: 3
num_layers: 1
num_heads: 4

# Negative Mining parameters:
num_negatives: 10
cl_start_ep: 10
cl_start_size: 218
curr_steps: ""
cl_update: 5

# Training Parameters
num_epochs: 40
batch_size: 2048
margin: 0.2
lr: 0.0002